robot_base_frame: $(arg prefix)base_footprint
transform_tolerance: 0.4
update_frequency: 5.0
publish_frequency: 5.0
obstacle_range: 3.0
#mark_threshold: 1
inflation_radius: 1.75
cost_scaling_factor: 2.58
publish_voxel_map: true
map_type: costmap
obstacles:
  scan: {sensor_frame: base_scan, data_type: LaserScan, topic: scan, marking: true, clearing: true}

